### ISSUE TITLE
Build fails with strange "missing files" error

### ISSUE THREAD

**Issue by ebenezergoose** [EasyNetDev/brscan-skey#2]
Thank you for your efforts in creating this. However, unfortunately the build fails for me and throws the following warnings and error...

```
dh_install: warning: Cannot find (any matches for) "/usr/share/doc/" (tried in ., debian/tmp)
dh_install: warning: brscan-skey-libsane1 missing files: /usr/share/doc/
dh_install: warning: Cannot find (any matches for) "/usr/share/doc/" (tried in ., debian/tmp)
dh_install: warning: brscan-skey-libsane missing files: /usr/share/doc/
dh_install: error: missing files, aborting
make: *** [debian/rules:15: binary] Error 255
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

I'm running Debian 13  'trixie' with kernel version 6.11.2-amd64. Libsane1 is installed. /usr/share/doc/libsane1 exists and has content. 

Any suggestions?

**Comment by EasyNetDev** [comment]
Hi @ebenezergoose,

Thanks for mentioning this issue. I not aware about this problem yet.
Also I'm using Debian 13 Trixie, so I will try to replicate it on my systems. I will come with an update.

**Comment by ebenezergoose** [comment]
Thank you kindly, that would be very much appreciated. :-)

**Comment by EasyNetDev** [comment]
I understand your frustration about software support in Linux. 
Believe me that I'm upset on these companies that are not take care too much about Linux systems.

**Comment by ebenezergoose** [comment]
It is frustrating at times, though TBH I think overall GNU/Linux support is a lot better than it used to be - largely thanks to people such as yourself.  And Trixie is a "testing" distro - so one must expect "new version" type issues that one would not encounter in the "stable" branch.

I don't know if this helps you resolve this issue any way, but I just found that a proposed solution in the Ubuntu fora for Ubuntu 24.04 LTS actually makes the original brscan-skey usable on Trixie too. Ubuntu 24.04 came from essentially the same generation "Sid" that Trixie did. And it also uses Libsane1 instead of Libsane. Granted, this workaround is a bit of a hack, requires a copy of Brother's brscan-skey-0.3.2-0.amd64.deb, extracting its innards, changing the dependency and rebuilding the package again. But I thought you may wish to take a look anyway, if you haven't already seen it...

```
dpkg -x brscan-skey-0.3.2-0.amd64.deb brscan-skey
dpkg -e brscan-skey-0.3.2-0.amd64.deb brscan-skey/DEBIAN
sed -i  -e 's/, libsane (>= 1.0.11-3)//g' brscan-skey/DEBIAN/control
sed -i  -e 's/, libsane (>= 1.0.11-3)//g' brscan-skey/DEBIAN/control.tmp
dpkg-deb -b brscan-skey brscan-skey-0.3.2-0.amd64.deb
```

[https://askubuntu.com/questions/1521411/ubuntu-24-04-brscan-skey-and-libsane-issue](https://askubuntu.com/questions/1521411/ubuntu-24-04-brscan-skey-and-libsane-issue )

**Comment by EasyNetDev** [comment]
Indeed was an empty folder /usr/share/doc/ which git is not uploading by default. So, I removed from brscan-skey-libsane1.install
