### ISSUE TITLE
Typo in the instudctions

### ISSUE THREAD

**Issue by ebenezergoose** [EasyNetDev/brscan-skey#3]
I hope you don't mind me mentioning it but there seems to be a wee typo in the instructions...
`git clone https://github.dev/EasyNetDev/brscan-skey`

Should read...
`git clone https://github.com/EasyNetDev/brscan-skey`

The "github.dev" site is the github editor. If one tries to clone it, it throws an error.  Or it certainly does for me. 
```
git clone https://github.dev/EasyNetDev/brscan-skey
Cloning into 'brscan-skey'...
fatal: https://github.dev/EasyNetDev/brscan-skey/info/refs not valid: could not determine hash algorithm; is this a git repository?
```

I realise this is trivial because most people would work out the correct address. But I thought I should mention it anyway.

**Comment by EasyNetDev** [comment]
Thanks. I will correct them. 👌

**Comment by ebenezergoose** [comment]
Thank you. Irony is that I mistyped the intro to this post! lol. :-)

**Comment by EasyNetDev** [comment]
Fixed.
